apiVersion: apps.emqx.io/v1beta3
kind: EmqxPlugin
metadata:
  name: emqx-lwm2m
  namespace: default
spec:
  selector:
      "apps.emqx.io/instance": "emqx-ee"
  pluginName: emqx_lwm2m
  config:
      "lwm2m.lifetime_min": "1s"
      "lwm2m.lifetime_max": "86400s"
      "lwm2m.bind.udp.1": "0.0.0.0:5683"
      "lwm2m.bind.udp.2": "0.0.0.0:5684"
      "lwm2m.bind.udp.3": "0.0.0.0:5685"
      "lwm2m.xml_dir": "/opt/emqx/etc/lwm2m_xml"