name: Release emqx operator

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check image tag for yaml
        run: |
          tag=$(cat config/samples/operator/controller.yaml | egrep "image:[[:space:]]emqx/emqx-operator-controller" | sed -r 's|image:[[:space:]]emqx/emqx-operator-controller:(.*)|\1|g' | tr -d '[:space:]')
          if [ "$tag" != "${GITHUB_REF##*/}" ]; then
            echo "Need update image tag for config/samples/operator/controller.yaml"
            exit 1
          fi
      - name: Check appVersion for helm
        run: |
          appVersion=$(egrep "^appVersion" deploy/charts/emqx-operator/Chart.yaml | sed -r 's|^appVersion:[[:space:]]([0-9]+.[0-9]+.[0-9]+)$|\1|g')
          if [ "$appVersion" != "${GITHUB_REF##*/}" ]; then
            echo "Need update appVersion for Chart.yaml"
            exit 1
          fi
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ github.repository_owner }}/emqx-operator-controller
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          release_name: EMQ X Operator ${{ github.ref }} Released
          tag_name: ${{ github.ref }}
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

  helm:
    runs-on: self-hosted
    if: github.repository_owner == 'emqx'
    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Check appVersion for helm
        working-directory: deploy/charts/emqx-operator
        run: |
          appVersion=$(egrep "^appVersion" Chart.yaml | sed -r 's|^appVersion:[[:space:]]([0-9]+.[0-9]+.[0-9]+)$|\1|g')
          if [ "$appVersion" != "${GITHUB_REF##*/}" ]; then
            echo "Need update appVersion for Chart.yaml"
            exit 1
          fi
      - name: Create helm package
        working-directory: deploy/charts/emqx-operator
        run: helm package .
      - name: Update helm repo
        run: |
          sudo mv $(find deploy/charts/emqx-operator -name "*.tgz") /repos/charts
          sudo helm repo index /repos/charts